### ISSUE TITLE
Use distribution package as alternative

### ISSUE THREAD

**Issue by oxr463** [lelutin/puppet-asterisk#16]
Basically I want to use the Debian/Ubuntu package, with your configuration options.

```puppet
Package { 'asterisk':
  ensure   => latest,
  provider => apt
}
```

<s>See also: https://wiki.ubuntu.com/AsteriskOnUbuntu</s>

See: https://packages.ubuntu.com/search?keywords=asterisk

**Comment by lelutin** [comment]
Hi @oxr463, please tell me if I misunderstood something:

This module installs the distro's package by default. The package name is configurable, but defaults to 'asterisk', which is the name for the package at least in debian and ubuntu

see:
* https://github.com/lelutin/puppet-asterisk/blob/master/manifests/init.pp#L99
* https://github.com/lelutin/puppet-asterisk/blob/master/manifests/install.pp#L12

Is there some functionality missing with regards to how you'd like to install the package (e.g. maybe the "ensure => latest" part)?

**Comment by oxr463** [comment]
Hmm, I think I may have misunderstood. @CNEddie, did you not say it was building from source?
