### ISSUE TITLE
include asterisk fails

### ISSUE THREAD

**Issue by booo** [lelutin/puppet-asterisk#2]
A pure `include asteriks` as stated in the README does not work:

```
==> voip: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> voip: Error: "" is not an Array.  It looks to be a String at /tmp/vagrant-puppet/modules-d7a4550e980cedc7050677f60754a8ba/asterisk/manifests/init.pp:49 on node voip.berlin.freifunk.net
==> voip: Error: "" is not an Array.  It looks to be a String at /tmp/vagrant-puppet/modules-d7a4550e980cedc7050677f60754a8ba/asterisk/manifests/init.pp:49 on node voip.berlin.freifunk.net
```
I guess some default values are missing for the iax_options.

**Comment by lelutin** [comment]
ah! indeed, there's no "allow" option in the default hash in params.pp

I'll see what that value is in the default iax.conf file from debian's package and use that in params.pp

**Comment by lelutin** [comment]
gah I missed my auto-close comment in the commit message :p 
closing this manually.

thanks for spotting and reporting this!

**Comment by booo** [comment]
Thanks for the blazing fast response.
